config/routes.rb
DailyRecord::Application.routes.draw do
  devise_for :users
  resources :tracks

  root to: "tracks#index"

end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user
  has_attached_file :audio

  validates_attachment_content_type :audio, :content_type => ['audio/mp3','audio/mpeg','audio/wav']  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @tracks = Track.all
  end

  def show
  end

  def new
    @track = current_user.tracks.build
  end

  def edit
  end

  def create
    @track = current_user.tracks.build(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    def correct_user
      @track = current_user.tracks.find_by(id: params[:id])
      redirect_to tracks_path, notice: "Not authorized to edit this track" if @track.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:author, :title, :reflection, :audio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_header.html.erb
<div id='primary-nav'
     >
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <li><%= link_to 'Tracks', tracks_path %></li>
      <li><%= link_to 'New Track', new_track_path %></li>
    <% else %>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
    <% end %>
  </ul>

  <div class="messages">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</div>

<div id='title'
     >
  <em><span class='daily'>Daily</span></em>
  <span class='record'>Record</span>
</div>

<script>
  
</script>

app/views/layouts/_signup.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Track', new_track_path %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %> to add your own tracks!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Daily Record</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div id='skrollr-body'>  
    <div style="margin: 100px 0 0 0;">
      <div class="container">
	<%= yield %>
      </div>
    </div>
  </div>

  <script>
   (function($){
     skrollr.init({
       forceHeight: false,
       smoothScrolling: false
     }).refresh();
   } (jQuery));
  </script>


</body>
</html>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :reflection %><br>
    <%= f.text_area :reflection %>
  </div>
  <div class="form-group">
    <%= f.label :audio %>
    <%= f.file_field :audio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
  <table class='table table-striped table-hover table-responsive tracks'
	 >
    <thead style="display:none;"
	   data-0='opacity:0.9;'
	   data-150='opacity:0;'
	   >
      <tr>
	<th>Title</th>
	<th>Reflection</th>
	<th>Audio</th>
	<% if user_signed_in? %>
	  <th></th>
	  <th></th>
	<% end %>
      </tr>
    </thead>

    <tbody>
      <tr style='height:150px;'>
	<td></td>
	<td></td>
	<td style='position:absolute;top:10px;right:-150px;'><%= render 'layouts/signup' %></td>
      </tr>
      <% @tracks.reverse.each do |track| %>
	<tr>
          <!--<td><%#= track.user.email if track.user %></td>-->
          <td><%= track.title %></td>
          <td><%= track.reflection %></td>
          <td><%= audio_tag(track.audio.url, controls: true, class: "mejs-player") %></td>
          <td><%= link_to 'Show', track %></td>
	  <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_track_path(track) %></td>
            <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  <% end %>
	</tr>
      <% end %>
    </tbody>
  </table>


<br>

<% if user_signed_in? %>
  <%= link_to 'New Track', new_track_path %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %> to add your own tracks!
<% end %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @track.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Reflection:</strong>
  <%= @track.reflection %>
</p>

<p>
  <strong>Audio:</strong>
  <%= audio_tag(@track.audio.url, controls: true, class: "mejs-player") %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_track_path(@track) %> |
<% end %>
<%= link_to 'Back', tracks_path %>